# Generated by Django 3.1.4 on 2020-12-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_remove_order_total_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchase_date',
            field=models.DateField(auto_now=True),
        ),
    ]
