# Generated by Django 3.1.4 on 2020-12-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_order_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='inactive',
            field=models.BooleanField(default=False, verbose_name='Inactive'),
        ),
        migrations.AddField(
            model_name='order',
            name='inactive',
            field=models.BooleanField(default=False, verbose_name='Inactive'),
        ),
        migrations.AddField(
            model_name='product',
            name='inactive',
            field=models.BooleanField(default=False, verbose_name='Inactive'),
        ),
        migrations.AddField(
            model_name='qualitylot',
            name='inactive',
            field=models.BooleanField(default=False, verbose_name='Inactive'),
        ),
    ]
