# Generated by Django 3.1.4 on 2020-12-27 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0004_auto_20201226_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(limit_choices_to={'inactive': False}, on_delete=django.db.models.deletion.PROTECT, to='general.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(limit_choices_to={'inactive': False}, to='general.Product', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(limit_choices_to={'inactive': False}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Seller'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quality_lot',
            field=models.ForeignKey(limit_choices_to={'inactive': False}, on_delete=django.db.models.deletion.PROTECT, to='general.qualitylot', verbose_name='Quality Lot'),
        ),
    ]
