# Generated by Django 3.1.4 on 2020-12-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20201226_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Total Value'),
            preserve_default=False,
        ),
    ]
