# Generated by Django 3.1.4 on 2020-12-27 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_order_total_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_value',
        ),
    ]
