# Generated by Django 3.1.4 on 2020-12-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_order_total_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, verbose_name='Total Value'),
        ),
    ]
