# Generated by Django 3.1.4 on 2020-12-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_auto_20201227_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_value',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Total Value'),
        ),
    ]
